# Generated by Django 3.1.7 on 2021-08-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_auto_20210825_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='primary',
        ),
        migrations.AddField(
            model_name='condition',
            name='main',
            field=models.ManyToManyField(related_name='mainSymptom', to='checker.Symptom'),
        ),
    ]
